version: '3.1'

services:
  db:
    image: mysql:5.5
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.1/16a